KafkaServer {
    org.apache.kafka.common.security.plain.PlainLoginModule required
    username="internal-kafka-admin"
    password="internal-kafka-admin-secret"
    user_admin="admin-secret"
    user_producer="producer-secret"
    user_flink="flink-secret";
};