apiVersion: 1
groups:
  - orgId: 1
    name: Kafka-Flink-Alerts
    folder: Flink Pipeline Alerts
    interval: 10s
    rules:
      - uid: consumer_lag_alert
        title: High Consumer Lag
        condition: A
        data:
          - refId: A
            datasourceUid: prometheus-default
            relativeTimeRange:
              from: 600
              to: 0
            model:
              expr: flink_taskmanager_job_task_operator_KafkaSourceReader_KafkaConsumer_records_lag_max > 10
              intervalMs: 1000
              maxDataPoints: 43200
        noDataState: OK
        execErrState: Error
        for: 10s
        annotations:
          summary: "Kafka Consumer Lag is high (>10)"
        labels:
          severity: warning